name: 787a68-sync
on:
  schedule:
    - cron: '20 1/12 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-787a68-GithubSync
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }}
    runs-on: ubuntu-latest
    # if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync 787a68-GithubSync
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/787a68/Rules.git"
          source_branch: "master"
          destination_branch: "787a68"
          github_token: ${{ secrets.PAT }}
